# Conduit
version: '3'
services:
    matrix:
        image: matrixconduit/matrix-conduit:latest
        restart: unless-stopped
        ports:
            - 8448:6167
        volumes:
          - matrix_db:/var/lib/matrix-conduit/:Z
        environment:
            CONDUIT_SERVER_NAME: aadityadhruv.com
            CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
            CONDUIT_DATABASE_BACKEND: rocksdb
            CONDUIT_PORT: 6167
            CONDUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
            CONDUIT_ALLOW_REGISTRATION: 'false'
            CONDUIT_ALLOW_FEDERATION: 'true'
            CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
            CONDUIT_ADDRESS: 0.0.0.0
            CONDUIT_CONFIG: '' 
