version: "3"
services:
  radicale:
    container_name: radicale
    image: tomsquest/docker-radicale
    privileged: true
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    environment:
      - TAKE_FILE_OWNERSHIP=false
    ports:
      - 5232:5232
    volumes:
      radicale_data:/data:Z
    restart: unless-stopped
