version: "3"
services:
  caddy:
    container_name: caddy
    privileged: true
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 4000:4000
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
    restart: unless-stopped

