version: "3"

services:
  dashboard:
    image: pawelmalak/flame
    container_name: flame 
    ports:
      - 8080:5005
    volumes:
      - ./data:/app/data:Z
      - ./backgrounds:/app/public/backgrounds:Z
    secrets:
      - password
    environment:
      - PASSWORD_FILE=/run/secrets/password
    restart: unless-stopped

secrets:
  password:
    external: true
