version: "3"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - USER=admin
      - PASS=****
    volumes:
      - transmission_config:/config
      - ./downloads:/downloads:Z
      - transmission_watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
