version: 3
services:
  docker_runner:
    image: drone/drone-runner-docker:1
    container_name: runner 
    privileged: true
    environment:
      - DRONE_RPC_SECRET=****
      - DRONE_RPC_HOST=dev.aadityadhruv.com
      - DRONE_RPC_PROTO=https
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=docker_runner
    ports:
      - 3081:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
